### ISSUE TITLE
Add support for enabling Oxtrust API upon installation

### ISSUE THREAD

**Issue by mogluu** [GluuFederation/enterprise-edition#15]
The target is to fully automate the gluu installation from CI pipeline. I think its also worth the while to add options to enable and disable casa related scripts, passport, and radius upon installation disregarding the fact that it can be done from oxtrust API. This would ease the installation process to make it clean without intervention from user.

**Comment by mogluu** [comment]
oxTrust API and Test mode control has been added to the docker image. The manifests will be updated to accommodate for this change. Official changes have not been made yet.

**Comment by iromli** [comment]
Note, the state of oxTrust API in 4.0 is experimental. There might be overhaul in upcoming version that may not backward-compatible.

**Comment by iromli** [comment]
oxTrust API UMA mode worked, but unfortunately latest oxAuth/oxTrust 4.0.1.Final build has issue that blocking users to login.

Here's the stacktrace from `oxauth.log`:

```
2019-11-30 03:27:50,225 INFO  [qtp859417998-14] [org.gluu.oxauth.auth.Authenticator] (Authenticator.java:426) - Authentication success for User: 'admi
n'
2019-11-30 03:27:50,293 ERROR [qtp859417998-19] [org.gluu.service.cache.NativePersistenceCacheProvider] (NativePersistenceCacheProvider.java:139) - Fa
iled to put entry, key: 51b462c6-7cfe-4d70-b2ef-9b77a153bbfe, hashedKey: 8e4adf859b0363f1fa79796866d6d1bf2d70e3cd699a29257c6327f3b488fd0b, message: Fa
iled to persist entry: uuid=8e4adf859b0363f1fa79796866d6d1bf2d70e3cd699a29257c6327f3b488fd0b,ou=cache,o=gluu
org.gluu.persist.exception.EntryPersistenceException: Failed to persist entry: uuid=8e4adf859b0363f1fa79796866d6d1bf2d70e3cd699a29257c6327f3b488fd0b,o
u=cache,o=gluu
        at org.gluu.persist.ldap.impl.LdapEntryManager.persist(LdapEntryManager.java:188) ~[oxcore-persistence-ldap-4.0.1.Final.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.persist(BaseEntryManager.java:117) ~[oxcore-persistence-core-4.0.1.Final.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.gluu.persist.EntityManager$PersistenceEntryManager$1948486608$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[weld-core-impl-3.1.1.
Final.jar:?]
        at org.gluu.service.cache.NativePersistenceCacheProvider.put(NativePersistenceCacheProvider.java:137) [oxcore-service-4.0.1.Final.jar[47/1872]
        at org.gluu.service.cache.NativePersistenceCacheProvider$Proxy$_$$_WeldClientProxy.put(Unknown Source) [oxcore-service-4.0.1.Final.jar:?]
        at org.gluu.service.cache.CacheProvider$Proxy$_$$_WeldClientProxy.put(Unknown Source) [oxcore-service-4.0.1.Final.jar:?]
        at org.gluu.service.BaseCacheService.put(BaseCacheService.java:86) [oxcore-service-4.0.1.Final.jar:?]
        at org.gluu.service.BaseCacheService.put(BaseCacheService.java:141) [oxcore-service-4.0.1.Final.jar:?]
        at org.gluu.service.CacheService$Proxy$_$$_WeldClientProxy.put(Unknown Source) [oxcore-service-4.0.1.Final.jar:?]
        at org.gluu.oxauth.service.SessionIdService.putInCache(SessionIdService.java:713) [classes/:?]
        at org.gluu.oxauth.service.SessionIdService.mergeWithRetry(SessionIdService.java:724) [classes/:?]
        at org.gluu.oxauth.service.SessionIdService.updateSessionId(SessionIdService.java:698) [classes/:?]
        at org.gluu.oxauth.service.SessionIdService$Proxy$_$$_WeldClientProxy.updateSessionId(Unknown Source) [classes/:?]
        at org.gluu.oxauth.auth.Authenticator.updateSession(Authenticator.java:475) [classes/:?]
        at org.gluu.oxauth.auth.Authenticator.prepareAuthenticationForStepImpl(Authenticator.java:725) [classes/:?]
        at org.gluu.oxauth.auth.Authenticator.prepareAuthenticationForStep(Authenticator.java:610) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:247) [org.mortbay.jasper.apache-el-8.5.35.1.jar:8.5.24]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) [org.mortbay.jasper.apache-el-8.5.35.1.jar:8.5.24]
        at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) [weld-web-3.1.1.Final.jar:3.1.1.Fin
al]
        at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) [weld-web-3.1.1.Final.jar:3.1.1.Final]
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:107) [javax.faces-2.3.9.jar:2.3.9]
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87) [javax.faces-2.3.9.jar:2.3.
9]
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102) [javax.faces-2.3.9.jar:2.3.9]
        at javax.faces.component.UIViewAction.broadcast(UIViewAction.java:587) [javax.faces-2.3.9.jar:2.3.9]
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:870) [javax.faces-2.3.9.jar:2.3.9]
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1418) [javax.faces-2.3.9.jar:2.3.9]
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:82) [javax.faces-2.3.9.jar:2.3.9]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100) [javax.faces-2.3.9.jar:2.3.9]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201) [javax.faces-2.3.9.jar:2.3.9]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:670) [javax.faces-2.3.9.jar:2.3.9]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873) [jetty-servlet-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623) [jetty-servlet-9.4.15.v20190215.jar:9.4.15.v2019021
5]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214) [websocket-server-9.4.15.v20190215.jar:
9.4.15.v20190215]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) [jetty-servlet-9.4.15.v20190215.jar:9.4.15.[9/1872]
5]
        at org.gluu.oxauth.audit.debug.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:67) [classes/:?]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602) [jetty-servlet-9.4.15.v20190215.jar:9.4.15.v2019021
5]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540) [jetty-servlet-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480) [jetty-servlet-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220) [jetty-server-9.4.15.v20190215.jar:9.4.
15.v20190215]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.Server.handle(Server.java:502) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267) [jetty-server-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.15.v20190215.jar:9.4.15.v20190215
]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [jetty-io-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215
]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.15.v20190215.jar:9
.4.15.v20190215]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.15.v20190215.jar:9.4.15.v20190215]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.gluu.persist.exception.operation.DuplicateEntryException: Entry already exists
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.addEntryImpl(LdapOperationsServiceImpl.java:716) ~[oxcore-persistence-ldap-4
.0.1.Final.jar:?]
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.addEntry(LdapOperationsServiceImpl.java:699) ~[oxcore-persistence-ldap-4.0.1
.Final.jar:?]
        at org.gluu.persist.ldap.impl.LdapEntryManager.persist(LdapEntryManager.java:181) ~[oxcore-persistence-ldap-4.0.1.Final.jar:?]
        ... 76 more
```

/cc @yurem

**Comment by iromli** [comment]
The feature has been added to latest images:

1. `gluufederation/config-init:4.0.1_05` (added test mode client ID and secret)
2. `gluufederation/persistence:4.0.1_05` (added test mode client)
3. `gluufederation/oxauth:4.0.1_05` (added JKS and JWKS for generating JWT)
4. `gluufederation/oxtrust:4.0.1_05` (added oxTrust API JAR)

Docs and example at https://www.gluu.org/docs/de/4.0/operation/oxtrust-api/

**Comment by mogluu** [comment]
https://www.gluu.org/docs/de/4.0/operation/oxtrust-api/ docs have been updated. Working with kubernetes setup as well. 

The following have been added and supported: 
- Auto enable passport, casa, SAML, radius, oxtrust API, UMA and oxtrust API Test Mode

Closing this issue.
